#!/bin/sh

Data Cut: 02/16/2015
Initial CSV file: 38647 Opportunities.

Data cleanup steps:
1) Remove Test Oppts: 34
2) Remove 'Estimated Value' outliers: 81
3) Remove 'Estimated Close Date' putliers: 2
Total Oppts: 38530
4) Replace 'NULL' with empty space
5) ~5K Oppts mass imported on 05/07/2010. Some were retroactive, causing wrong dates. Removed on code.

Data enhancement:
1) 244 Open Oppts have 'Actual Close Date' value. CRM bug ?
2) Set 'Market' value for 12 Oppts. Got value from 'Created By' user.

Intended Features
- CreatedOn (split in Year, Month and Day features)
- Billing Frequency
- Cost Center
- Functional Area
- National Support
- # of Resources
- Project Type
- Reopened Oppt.
- Specialty
- Win Wire Inclusion
- Est. Bill Rate
- Primary Work Tag
- Project Duration
- Days Open
- # of Emails for Oppt.
- # of Meetings for Oppt.
- # of Tasks for Oppt.
- Has BDM
- Has CSP
- Has SSP
- # of Oppt for Account
- # of Lost Oppt for Account
- # of Open Oppt for Account
- # of Won Oppt for Account
- # of Oppt for Account and Market
- Market
- Sales Stage Code


Notes:
- with Sales Stage Code as is, model predicted only 20 Won (CRM had 78), but got 19 correctly. Planning on setting Sales Statge Code for Won and Lost to 100000005
    - with new CRM file. Model said 32 Won, in CRM: 27 Won and 5 Lost. Total CRM Won: 127
- with Sales Stage Code as 99999999 for Lost Oppts, model predicted 161 Lost Oppts, and out of those, 153 were Lost in CRM. CRM had 249 total Lost Oppt.
- with Sales Stage Code as 100000002.1 (Sales Stage Code average for Lost Oppts) for Lost Oppts,
    - model predicted 265 Lost Oppts, and out of those, 223 were Lost in CRM. CRM had 249 total Lost Oppt. - 89.55%
    - model predicted 111 Won Oppts, and out of those, 88 were Won in CRM. CRM had 127 total Won Oppt. - 69.3%
    - Lost rate = 66.22%
    - Win rate = 33.77%
    - General model accuracy: 83.51% - code has a .merge() by Oppt. name. There are duplicated Oppt names, cause a few Oppts (5 or so. dropping accuracy to 82.71%) to appear twice in the excel file. Will deal with that later.


